packages:
  - packages/*
  - apps/*

catalog:
  '@crxjs/vite-plugin': ^2.1.0
  '@cspell/eslint-plugin': ^9.2.0
  '@dotenvx/dotenvx': ^1.48.4
  '@eslint/css': ^0.10.0
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.32.0
  '@microsoft/api-extractor': ^7.52.8
  '@next/eslint-plugin-next': ^15.4.6
  '@opennextjs/cloudflare': ^1.6.5
  '@paralleldrive/cuid2': ^2.2.2
  '@playwright/test': ^1.54.2
  '@pnpm/lockfile.fs': ^1001.1.14
  '@pnpm/types': ^1000.6.0
  '@pnpm/workspace.pkgs-graph': ^1000.0.15
  '@radix-ui/react-dropdown-menu': ^2.1.15
  '@radix-ui/react-slot': ^1.2.3
  '@react-hookz/web': ^25.1.1
  '@storybook/builder-vite': ^9.1.1
  '@storybook/react-vite': ^9.1.1
  '@tailwindcss/postcss': ^4.1.11
  '@tailwindcss/vite': ^4.1.11
  '@tanstack/react-query': ^5.84.1
  '@trpc/client': 11.4.3
  '@trpc/react-query': 11.4.3
  '@trpc/server': 11.4.3
  '@types/chrome': ^0.1.1
  '@types/eslint': ^9.6.1
  '@types/eslint-config-prettier': ^6.11.3
  '@types/js-cookie': ^3.0.6
  '@types/node': ^22.17.0
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.7
  '@typescript/native-preview': 7.0.0-dev.20250806.1
  '@vitejs/plugin-react-swc': ^3.11.0
  better-sqlite3: ^12.2.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  concurrently: ^9.2.0
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.4
  eslint: ^9.32.0
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.4
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-storybook: ^9.1.1
  globals: ^16.3.0
  js-cookie: ^3.0.5
  lucide-react: ^0.536.0
  motion: ^12.23.12
  nanoid: ^5.1.5
  next: ^15.4.6
  next-themes: ^0.4.6
  nodemon: ^3.1.10
  playwright: ^1.53.2
  prettier: ^3.6.2
  prettier-plugin-organize-imports: ^4.2.0
  react: ^19.1.1
  react-dom: ^19.1.1
  react-scan: ^0.4.3
  server-only: ^0.0.1
  storybook: ^9.1.1
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.8
  tsx: ^4.20.3
  tw-animate-css: ^1.3.6
  typescript: ~5.8.0
  typescript-eslint: ^8.39.0
  universal-cookie: ^8.0.1
  usehooks-ts: ^3.1.1
  vite: ^7.0.5
  vite-plugin-zip-pack: ^1.2.4
  vitest: ^3.2.4
  wrangler: ^4.28.0
  zod: 3.25.73
  eslint-plugin-better-tailwindcss: ^3.7.4
  webextension-polyfill: ^0.12.0
  '@types/webextension-polyfill': ^0.12.3
  text-fragments-polyfill: ^6.4.1
  radix-ui: ^1.4.2
  '@faker-js/faker': ^9.9.0
  postcss: ^8.5.6
  sonner: ^2.0.7
  '@vitejs/plugin-react': ^4.7.0

catalogMode: strict

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

patchedDependencies:
  eslint-plugin-storybook: patches/eslint-plugin-storybook.patch
  vite-plugin-zip-pack: patches/vite-plugin-zip-pack.patch
  text-fragments-polyfill: patches/text-fragments-polyfill.patch
