packages:
  - packages/*
  - apps/*

catalog:
  '@crxjs/vite-plugin': ^2.0.3
  '@cspell/eslint-plugin': ^9.2.0
  '@dotenvx/dotenvx': ^1.45.2
  '@eslint/css': ^0.8.1
  '@eslint/eslintrc': ^3.3.1
  '@eslint/js': ^9.32.0
  '@microsoft/api-extractor': ^7.52.8
  '@next/eslint-plugin-next': ^15.4.5
  '@opennextjs/cloudflare': ^1.4.0
  '@paralleldrive/cuid2': ^2.2.2
  '@playwright/test': ^1.53.2
  '@pnpm/lockfile.fs': ^1001.1.14
  '@pnpm/types': ^1000.6.0
  '@pnpm/workspace.pkgs-graph': ^1000.0.15
  '@radix-ui/react-dropdown-menu': ^2.1.15
  '@radix-ui/react-slot': ^1.2.3
  '@react-hookz/web': ^25.1.1
  '@simplewebauthn/browser': ^9.0.1
  '@simplewebauthn/server': ^9.0.2
  '@storybook/builder-vite': ^9.0.15
  '@storybook/react-vite': ^9.0.15
  '@tailwindcss/postcss': ^4.1.11
  '@tailwindcss/vite': ^4.1.8
  '@tanstack/react-query': ^5.81.5
  '@trpc/client': ^11.4.3
  '@trpc/react-query': ^11.4.3
  '@trpc/server': ^11.4.3
  '@types/chrome': ^0.1.1
  '@types/eslint': ^9.6.1
  '@types/eslint-config-prettier': ^6.11.3
  '@types/js-cookie': ^3.0.6
  '@types/node': ^22.17.0
  '@types/react': ^19.1.6
  '@types/react-dom': ^19.1.5
  '@typescript/native-preview': 7.0.0-dev.20250801.1
  '@vitejs/plugin-react-swc': ^3.10.1
  better-sqlite3: ^12.2.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  concurrently: ^9.2.0
  drizzle-kit: ^0.31.4
  drizzle-orm: ^0.44.2
  eslint: ^9.32.0
  eslint-config-next: ^15.4.5
  eslint-config-prettier: ^10.1.8
  eslint-plugin-prettier: ^5.5.3
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-react-refresh: ^0.4.20
  eslint-plugin-storybook: ^9.1.0
  globals: ^16.3.0
  js-cookie: ^3.0.5
  lucide-react: ^0.525.0
  motion: ^12.18.1
  nanoid: ^5.1.5
  next: ^15.3.5
  next-auth: 5.0.0-beta.29
  next-themes: ^0.4.6
  nodemon: ^3.1.10
  playwright: ^1.53.2
  prettier: ^3.6.2
  prettier-plugin-organize-imports: ^4.2.0
  prettier-plugin-tailwindcss: ^0.6.14
  react: ^19.1.0
  react-dom: ^19.1.0
  react-scan: ^0.3.4
  resend: ^4.6.0
  server-only: ^0.0.1
  storybook: ^9.0.15
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.8
  tsx: ^4.20.3
  tw-animate-css: ^1.3.5
  typescript: ~5.9.2
  typescript-eslint: ^8.38.0
  universal-cookie: ^8.0.1
  usehooks-ts: ^3.1.1
  vite: ^7.0.5
  vite-plugin-zip-pack: ^1.2.4
  vitest: ^3.2.0
  wrangler: ^4.27.0
  zod: ^3.25.73

catalogMode: strict

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - unrs-resolver
  - workerd

patchedDependencies:
  eslint-plugin-storybook: patches/eslint-plugin-storybook.patch
  next: patches/next.patch
  vite-plugin-zip-pack: patches/vite-plugin-zip-pack.patch
