# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Playwright Tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build and test app-quotum-web

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Node.js with corepack
        uses: ./.github/actions/setup-node

      - name: Setup cache
        uses: ./.github/actions/setup-cache
        with:
          restore-key-prefix: 'cache-e2e'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Pre-build dependencies
        run: pnpm -w --workspace-concurrency -1 --filter "@quotum/app-quotum-web..." run build:tsc

      - name: Build application
        run: pnpm run build:opennext
        working-directory: apps/app-quotum-web

      - name: Prepare local database
        run: pnpm run db:migrate:local:apply
        working-directory: apps/app-quotum-web

      - name: Install Playwright browsers
        run: pnpm exec playwright install --with-deps
        working-directory: apps/app-quotum-web

      - name: Run Playwright tests
        run: pnpm run test:e2e
        working-directory: apps/app-quotum-web

      - name: Upload Playwright report
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: apps/app-quotum-web/playwright-report/
          retention-days: 30
